-- Auto-generated from schema-map-postgres.psd1 (map@mtime:2025-10-24T09:46:38Z)
-- engine: postgres
-- table:  notifications
CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NULL,
  channel TEXT NOT NULL,
  template VARCHAR(100) NOT NULL,
  payload JSONB NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  retries INTEGER NOT NULL DEFAULT 0,
  max_retries INTEGER NOT NULL DEFAULT 6,
  next_attempt_at TIMESTAMPTZ(6) NULL,
  scheduled_at TIMESTAMPTZ(6) NULL,
  sent_at TIMESTAMPTZ(6) NULL,
  error TEXT NULL,
  last_attempt_at TIMESTAMPTZ(6) NULL,
  locked_until TIMESTAMPTZ(6) NULL,
  locked_by VARCHAR(100) NULL,
  priority INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT chk_notifications_channel CHECK (channel IN ('email','push')),
  CONSTRAINT chk_notifications_status CHECK (status IN ('pending','processing','sent','failed'))
);
